# Generated by Django 5.2.17 on 2026-09-17 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('data_associacao', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de associação')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name_plural': 'associados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aviso', 'Aviso'), ('evento', 'Evento')], default='aviso', max_length=10)),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('texto', models.TextField()),
                ('data_evento', models.DateTimeField(blank=True, null=True, verbose_name='data e hora do evento')),
                ('local', models.CharField(blank=True, max_length=150)),
                ('publicado', models.BooleanField(default=True, verbose_name='publicar no mural')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1)),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('categoria', models.CharField(choices=[('mensalidade', 'Mensalidade'), ('doacao', 'Doação'), ('evento', 'Evento'), ('manutencao', 'Manutenção'), ('contas', 'Contas (água, luz, internet)'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.associado', verbose_name='associado (opcional)')),
            ],
            options={
                'verbose_name': 'lançamento',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
